### ISSUE TITLE
How to calculate an expression for each row of a large  data table without affecting performance 

### ISSUE THREAD

**Issue by prakashboston** [KovtunV/NoStringEvaluating#13]
I want to calculate an expression for each row of a data table and add a new column to the data table based on the result got.

**Comment by KovtunV** [comment]
To improve performance I suggest follow these recommendations:
1. Use variables dictionary instead of concatenation `IDictionary<string, EvaluatorValue> variables`
2. Tune your custom functions: dont allocate extra memory, etc
3. If possible store FormulaNodes somewhere and pass to evaluator it instead of string formula.

This is a general recommendarions, for more specific I need more details, if possible - examples

**Comment by prakashboston** [comment]
In a data table, a formula column allows you to perform calculations based on values from other columns. Let's say you have a data table with columns "Quantity" and "Price," and you want to add a formula column for "Total" (Quantity multiplied by Price). The formula in the "Total" column multiplies the corresponding values in the "Quantity" and "Price" columns. 
How to perform this operation using our engine

**Comment by KovtunV** [comment]
If we work with numbers only so only these recommendations:
1) use single evaluator object
2) Use variables dictionary IDictionary<string, EvaluatorValue> variables
3) If possible store FormulaNodes somewhere and pass to evaluator it instead of string formula

3 is a really optional you can go with defaults (string formula).

So design can be like:
loop by rows
from the row take two variables Quantity and Price
send to formula
store in a Total column

snippet:
```csharp
    static void Main()
    {
        var ns = CreateNoString();

        // store a single instance (or one per thread)
        var variables = new Dictionary<string, EvaluatorValue>();

        // fetch data from the row
        var quantity = 14;
        var price = 123.675;

        // update dictionary
        variables["Quantity"] = quantity;
        variables["Price"] = price;

        // calculate total
        var total = ns.CalcNumber("Quantity * Price", variables); // 1731,45
    }
```

**Comment by KovtunV** [comment]
So you have variables like A2 B2, they should be in a dictionary. Also you have to store all cell formulas with linking to cells somewhere to understand what formula should be reruned.

For example
formula: "A2*B2"
I store this CellFormula
After changing A2 or B2 you should say "Hey, I updated A2 has anybody listen to this cell?"
our Total cell with formula (A2*B2) will take this notification

take values from A2 and B2
put into dictionary
send to evaluator
update Total cell value


OR, if this is too difficult just run for every formula and update all formulas after any changing ¯\_(ツ)_/¯

**Comment by KovtunV** [comment]
Sure, if I were you I would add Interface into the row `IVariablesContainer` (if you can extend DataRow) and use row as is
```csharp

    // calculate total
    var total = row["total"] =ns.CalcNumber("quantity * price", row); ;

```

without iterating you should implement some notification service, or maybe MediatR can be usefull here

**Comment by KovtunV** [comment]
I meant we can use it for notifications when some cell is changes we need to notify all cells with formula that uses it. Perhaps that's a bad solution, yes. But with notifications we don't need to run through the all rows.

I don't have a sample because I just imagine what can we do
