### ISSUE TITLE
semicolons or commas

### ISSUE THREAD

**Issue by chenxiang-linkmore** [KovtunV/NoStringEvaluating#7]
For a very, very powerful project, why do you use semicolons instead of commas as separators between variables? Is there any special consideration? Do you support replacing with commas? Thank you~

**Comment by KovtunV** [comment]
@chenxiang-linkmore Hello, probably due to option SetFloatingPointSymbol, some cultures use comma as separaor like 12,44
I suppose didn't want to think how to parse arguments like sum(12,33, 35,6), here are two numbers in case if comma is floating point separator.

Thanks for an idea will try to implement in a next release!

**Comment by chenxiang-linkmore** [comment]
i got it....

**Comment by KovtunV** [comment]
@chenxiang-linkmore Hey, in a version **2.4.2** you can use comma as well. [More details about release](https://www.nuget.org/packages/NoStringEvaluating#release-body-tab)
